/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei"
import React, { useRef } from "react"

export default function Avatar(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF("/avatar.glb")

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["4_Object06_01_16_16001"].geometry}
        material={nodes["4_Object06_01_16_16001"].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["4_Object06_01_16_16002"].geometry}
        material={nodes["4_Object06_01_16_16002"].material}
        position={[0, 0.25, 0]}
      />
      <group position={[0, 0.25, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["4_Object06_01_16_16_1"].geometry}
          material={nodes["4_Object06_01_16_16_1"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["4_Object06_01_16_16_2"].geometry}
          material={materials["4_Object08_0.1_16_16"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.model002.geometry}
        material={materials["material_0.001"]}
        position={[-0.13, -1.35, -1.06]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[22.81, 22.81, 22.81]}
      />
    </group>
  )
}

useGLTF.preload("/photo-realistic.glb")
